### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mharsch**
sudo needed for this line

### CODE REVIEW

**Comment by geerlingguy** [comment]
It shouldn't be required if you're logged in as the Pi user. Maybe the guide should reflect you can do this on other user accounts too.

**Comment by mharsch** [comment]
Are you sure?

`pi@thermopi:~/pi-kiosk $ cp kiosk.service /lib/systemd/system/kiosk.service
cp: cannot create regular file '/lib/systemd/system/kiosk.service': Permission denied`

**Comment by mharsch** [comment]
System info.  Running on Pi 3 installed this week (32-bit bookwork - full), everything up to date.

`pi@thermopi:~ $ id
uid=1000(pi) gid=1000(pi) groups=1000(pi),4(adm),20(dialout),24(cdrom),27(sudo),29(audio),44(video),46(plugdev),60(games),100(users),102(input),105(render),106(netdev),115(lpadmin),993(gpio),994(i2c),995(spi)
pi@thermopi:~ $ ls -ld /lib/systemd/system
drwxr-xr-x 30 root root 20480 Nov  8 09:44 /lib/systemd/system
pi@thermopi:~ $ uname -a
Linux thermopi 6.6.51+rpt-rpi-v7 #1 SMP Raspbian 1:6.6.51-1+rpt3 (2024-10-08) armv7l GNU/Linux
pi@thermopi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

**Comment by geerlingguy** [comment]
@mharsch but the line being changed here is the kiosk.sh line: `sudo cp kiosk.sh /home/pi/kiosk/kiosk.sh`

**Comment by mharsch** [comment]
Doh!  Wrong line changed.  See latest change.

**Comment by geerlingguy** [comment]
@mharsch hehe there you go!

**Pull request merged**
